configuration:
  reload-message: '<green>Плагин успешно перезапущен.'
  spawn-set-message: '<green>Spawn успешно установлен.'

  spawn-command-message: '<green>Вы были телепортированы на spawn.'
  spawn-command-other-sender: '<green>Вы успешно телепортировали игрока на spawn.'
  spawn-command-other-target: '<gray>Вас телепортировали на spawn.'

  teleport-on-join: true
  teleport-on-first-join: true

  teleport-when-player-fall-in-void: true
  teleport-when-player-death: true